services:
  caddy_server:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy_controller
      - caddy
    environment:
      - CADDY_DOCKER_MODE=server
      - CADDY_CONTROLLER_NETWORK=10.200.200.0/24
    volumes:
      # this volume is needed to keep the certificates
      # otherwise, new ones will be re-issued upon restart
      - ./data:/data
    labels:
      caddy_controlled_server:

  caddy_controller:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    networks:
      - caddy_controller
      - caddy
    environment:
      - CADDY_DOCKER_MODE=controller
      - CADDY_CONTROLLER_NETWORK=10.200.200.0/24
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  caddy:
    external: true
  caddy_controller:
    external: true
