services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'America/New_York'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - ./config:/etc/pihole
    networks:
      - caddy
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
    labels:
      caddy: pihole.edwardofclt.com
      caddy.reverse_proxy: "{{upstreams 80}}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/admin" ]
      interval: 30s
      timeout: 10s
      retries: 3
  updater:
    container_name: pihole-updater
    depends_on:
      - pihole
    build:
      context: ./local-dns-updater
      dockerfile: Dockerfile
    env_file:
      - ./local-dns-updater/.env
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

networks:
  caddy:
    external: true
