services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - ../media/downloads:/downloads
      - ../media/incomplete:/incomplete-downloads
    restart: unless-stopped
    networks:
    - caddy
    labels:
      caddy: nzb.edwardofclt.com
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  caddy:
    external: true
