services:
    deleterr:
        image: ghcr.io/rfsbraz/deleterr:latest
        container_name: deleterr
        environment:
            LOG_LEVEL: INFO
        volumes:
            - ./config:/config
            - ./logs:/config/logs
        restart: no
    scheduler:
        image: mcuadros/ofelia:latest
        container_name: scheduler
        depends_on:
            - deleterr
        command: daemon --docker
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
        labels:
            ofelia.job-run.deleterr.schedule: "@weekly"
            ofelia.job-run.deleterr.container: "deleterr"
